{
  flake.modules.nixos.adguardhome =
    { pkgs, lib, ... }:
    {
      virtualisation.oci-containers.containers."adguardhome" = {
        image = "docker.io/adguard/adguardhome";
        volumes = [
          "adguardhome_adguardhome-conf:/opt/adguardhome/conf:rw"
          "adguardhome_adguardhome-work:/opt/adguardhome/work:rw"
        ];
        ports = [
          "8053:53/tcp"
          "8053:53/udp"
          "8080:80/tcp"
          "3000:3000/tcp"
          "8443:443/tcp"
          "8443:443/udp"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=adguardhome"
          "--network=adguardhome_default"
        ];
      };
      systemd.services."podman-adguardhome" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        unitConfig.Description = "Container adguardhome generated by compose2nix.";
        after = [
          "podman-network-adguardhome_default.service"
          "podman-volume-adguardhome_adguardhome-conf.service"
          "podman-volume-adguardhome_adguardhome-work.service"
        ];
        requires = [
          "podman-network-adguardhome_default.service"
          "podman-volume-adguardhome_adguardhome-conf.service"
          "podman-volume-adguardhome_adguardhome-work.service"
        ];
        partOf = [
          "podman-compose-adguardhome-root.target"
        ];
        wantedBy = [
          "podman-compose-adguardhome-root.target"
        ];
      };

      # Networks
      systemd.services."podman-network-adguardhome_default" = {
        unitConfig.Description = "Network adguardhome_default generated by compose2nix.";
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f adguardhome_default";
        };
        script = ''
          podman network inspect adguardhome_default || podman network create adguardhome_default
        '';
        partOf = [ "podman-compose-adguardhome-root.target" ];
        wantedBy = [ "podman-compose-adguardhome-root.target" ];
      };

      # Volumes
      systemd.services."podman-volume-adguardhome_adguardhome-conf" = {
        unitConfig.Description = "Volume adguardhome_adguardhome-conf generated by compose2nix.";
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          podman volume inspect adguardhome_adguardhome-conf || podman volume create adguardhome_adguardhome-conf
        '';
        partOf = [ "podman-compose-adguardhome-root.target" ];
        wantedBy = [ "podman-compose-adguardhome-root.target" ];
      };
      systemd.services."podman-volume-adguardhome_adguardhome-work" = {
        unitConfig.Description = "Volume adguardhome_adguardhome-work generated by compose2nix.";
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          podman volume inspect adguardhome_adguardhome-work || podman volume create adguardhome_adguardhome-work
        '';
        partOf = [ "podman-compose-adguardhome-root.target" ];
        wantedBy = [ "podman-compose-adguardhome-root.target" ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."podman-compose-adguardhome-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };
}
