{
  flake.modules.nixos.twingate-hallowed-marten =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    {
      sops.secrets."twingate/connectors/hallowed-marten" = { };

      virtualisation.oci-containers.containers."twingate-hallowed-marten" = {
        image = "docker.io/twingate/connector:latest";
        environmentFiles = [
          config.sops.secrets."twingate/connectors/hallowed-marten".path
        ];
        labels = {
          "compose2nix.settings.sops.secrets" = "twingate/connectors/hallowed-marten";
          "io.containers.autoupdate" = "registry";
        };
        log-driver = "journald";
        extraOptions = [
          "--network-alias=twingate-hallowed-marten"
          "--network=twingate-hallowed-marten_default"
          "--sysctl=net.ipv4.ping_group_range=0 2147483647"
        ];
      };
      systemd.services."podman-twingate-hallowed-marten" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        unitConfig.Description = "Container twingate-hallowed-marten generated by compose2nix.";
        after = [
          "podman-network-twingate-hallowed-marten_default.service"
        ];
        requires = [
          "podman-network-twingate-hallowed-marten_default.service"
        ];
        partOf = [
          "podman-compose-twingate-hallowed-marten-root.target"
        ];
        wantedBy = [
          "podman-compose-twingate-hallowed-marten-root.target"
        ];
      };

      # Networks
      systemd.services."podman-network-twingate-hallowed-marten_default" = {
        unitConfig.Description = "Network twingate-hallowed-marten_default generated by compose2nix.";
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f twingate-hallowed-marten_default";
        };
        script = ''
          podman network inspect twingate-hallowed-marten_default || podman network create twingate-hallowed-marten_default
        '';
        partOf = [ "podman-compose-twingate-hallowed-marten-root.target" ];
        wantedBy = [ "podman-compose-twingate-hallowed-marten-root.target" ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."podman-compose-twingate-hallowed-marten-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };
}
