{
  flake.modules.nixos.twingate-quaint-starling =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    {
      sops.secrets."twingate/connectors/quaint-starling" = { };
      virtualisation.oci-containers.containers."twingate-quaint-starling" = {
        image = "docker.io/twingate/connector:latest";
        environmentFiles = [
          config.sops.secrets."twingate/connectors/quaint-starling".path
        ];
        labels = {
          "compose2nix.settings.sops.secrets" = "twingate/connectors/quaint-starling";
        };
        log-driver = "journald";
        extraOptions = [
          "--network-alias=twingate-quaint-starling"
          "--network=twingate-quaint-starling_default"
          "--sysctl=net.ipv4.ping_group_range=0 2147483647"
        ];
      };
      systemd.services."podman-twingate-quaint-starling" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        unitConfig.Description = "Container twingate-quaint-starling generated by compose2nix.";
        after = [
          "podman-network-twingate-quaint-starling_default.service"
        ];
        requires = [
          "podman-network-twingate-quaint-starling_default.service"
        ];
        partOf = [
          "podman-compose-twingate-quaint-starling-root.target"
        ];
        wantedBy = [
          "podman-compose-twingate-quaint-starling-root.target"
        ];
      };

      # Networks
      systemd.services."podman-network-twingate-quaint-starling_default" = {
        unitConfig.Description = "Network twingate-quaint-starling_default generated by compose2nix.";
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f twingate-quaint-starling_default";
        };
        script = ''
          podman network inspect twingate-quaint-starling_default || podman network create twingate-quaint-starling_default
        '';
        partOf = [ "podman-compose-twingate-quaint-starling-root.target" ];
        wantedBy = [ "podman-compose-twingate-quaint-starling-root.target" ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."podman-compose-twingate-quaint-starling-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };
}
