keys:
  - &admin_zach age193lc7hl63wl7xpzga9xsf674q5xvp9xxrlku9qr3xhah5ugz2qjqp3gr0a
  - &host_desktop age13vusmuzdm94pqskf0a9dereczad9ys846azpw6dfx94wvz5kyexqpagrme
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *admin_zach
        - *host_desktop
