services:
  adguardhome:
    image: docker.io/adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "5300:53/tcp"
      - "5300:53/udp"
      - "8000:80/tcp"
      - "3000:3000/tcp"
      - "4430:443/tcp"
      - "4430:443/udp"
      - "8530:853/tcp"
    volumes:
      - adguardhome-work:/opt/adguardhome/work
      - adguardhome-conf:/opt/adguardhome/conf
volumes:
  adguardhome-work:
  adguardhome-conf:
